name: Botpress Webhook Trigger

on: [push]

jobs:
  send-selected-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: '0' # Fetches all history for all branches and tags

    - name: Prepare and Send Files
      run: |
        # Create JSON payload file
        echo "{" > payload.json

        # Function to add file content to JSON payload
        add_file_to_payload() {
          echo "\"$1\": \"$(base64 -w 0 $1)\"," >> payload.json
        }

        # Find and process .md and .txt files
        find . -type f \( -name "*.md" -o -name "*.txt" \) -exec bash -c 'add_file_to_payload "$0"' {} \;

        # Find and process .html, .css, .js files at the ROOT level
        find . -maxdepth 1 -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) -exec bash -c 'add_file_to_payload "$0"' {} \;

        # Finalize JSON payload
        sed -i '$ s/,$//' payload.json # Remove last comma
        echo "}" >> payload.json

        # Send JSON payload to Botpress webhook
        curl -X POST \
             -H "Content-Type: application/json" \
             -d @payload.json \
             https://webhook.botpress.cloud/7675225e-133b-4413-9d4e-779b425c4952
